site_name: VenafiPS
theme:
  name: material
  logo: images/v.svg
  features:
    - navigation.expand
  palette:
    primary: indigo
repo_url: https://github.com/Venafi/VenafiPS
repo_name: VenafiPS
edit_uri: ""
docs_dir: docs
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: index.md
