site_name: VenafiPS
repo_url: https://github.com/Venafi/VenafiPS
site_author: Greg Brownstein
edit_uri: edit/main/docs/
theme: readthedocs
copyright: "Copyright (c) 2018-2021 Greg Brownstein"
pages:
  - Home: index.md
