site_name: VenafiPS PowerShell Module

copyright: Copyright &copy; 2026 CyberArk Software Ltd. All rights reserved.

theme:
  name: material
  # custom_dir: docs/overrides  #https://squidfunk.github.io/mkdocs-material/customization/#extending-the-theme
  logo: assets/images/logos/cyberark-logo-tagline.svg
  favicon: assets/images/logos/cyberark.png
  icon:
    repo: fontawesome/brands/github   # https://squidfunk.github.io/mkdocs-material/setup/setting-up-repository/#repository-icon
    annotation: material/plus-circle

  features:
    # - navigation.expand
    - navigation.sections   # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-sections
    - navigation.instant    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    # - navigation.tabs       # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.footer     # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#navigation
    - search.highlight      # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.suggest        # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.share          # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-sharing
    - announce.dismiss      # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/#announcement-bar
    - content.code.copy     # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.annotate # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code+anno#code-annotations
    - content.tabs.link     # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#linked-content-tabs
  # font:                     # Can use any google font.
  #   text: 'Public Sans'
  #   code: 'Roboto Mono'
  palette:                  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/?h=dark#color-palette-toggle
                            # Dark mode colors are set in assets/css/dark-mode.css
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

    # primary: indigo
repo_url: https://github.com/Venafi/venafips
repo_name: VenafiPS

extra_css:                  # Additional stylesheets to use on every page
  - assets/css/branding.css
  - assets/css/custom.css
  - assets/css/mini-card.css

extra:
  social:                   # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
    - icon: fontawesome/brands/github
      link: https://github.com/venafi
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/CyberArk
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/CyberArk/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/VenafiCo
    - icon: fontawesome/brands/facebook-f
      link: https://www.facebook.com/CyberArk
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/cyberark_corp/
    - icon: fontawesome/solid/rss
      link: https://www.cyberark.com/resources/all-blog-posts

# edit_uri: ""
markdown_extensions:
  admonition: {}              # https://python-markdown.github.io/extensions/admonition/
  abbr: {}                    # https://squidfunk.github.io/mkdocs-material/reference/abbreviations/ extension to add additional content on hover
  meta: {}
  attr_list: {}               # https://python-markdown.github.io/extensions/attr_list/
  def_list: {}                # https://python-markdown.github.io/extensions/definition_lists/
  toc:
    permalink: true       # Generate permanent links at the end of each header
    separator: "-"        # Replace any white space in generated IDs with a dash
    toc_depth: 2          # Two levels on the "On this page" menu
    title: On this page   # Sets the title of the topic toc
  pymdownx.details: {}        # Enables expandable sections https://facelessuser.github.io/pymdown-extensions/extensions/details/
  pymdownx.tabbed:         # Enables tabs https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
  pymdownx.superfences: {}    # Allows code samples to be nested in tabs https://facelessuser.github.io/pymdown-extensions/extensions/superfences/
  pymdownx.magiclink: {}      # Automatically links websites and email addresses https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
  pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
  md_in_html: {}              # Allows markdown to be within html elements https://github.com/Python-Markdown/markdown/blob/master/docs/extensions/md_in_html.md
  footnotes: {}
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Changelog: changelog.md
  - Functions:
    - Invoke-TrustRestMethod: functions/Invoke-TrustRestMethod.md
    - New-TrustClient: functions/New-TrustClient.md
    - Certificate Manager Self-Hosted:
      - Add-CmAdaptableHash: functions/Add-CmAdaptableHash.md
      - Add-CmCertificateAssociation: functions/Add-CmCertificateAssociation.md
      - Add-CmEngineFolder: functions/Add-CmEngineFolder.md
      - Add-CmTeamMember: functions/Add-CmTeamMember.md
      - Add-CmTeamOwner: functions/Add-CmTeamOwner.md
      - Convert-CmObject: functions/Convert-CmObject.md
      - Export-CmCertificate: functions/Export-CmCertificate.md
      - Export-CmVaultObject: functions/Export-CmVaultObject.md
      - Find-CmCertificate: functions/Find-CmCertificate.md
      - Find-CmClient: functions/Find-CmClient.md
      - Find-CmEngine: functions/Find-CmEngine.md
      - Find-CmIdentity: functions/Find-CmIdentity.md
      - Find-CmObject: functions/Find-CmObject.md
      - Find-CmVaultId: functions/Find-CmVaultId.md
      - Get-CmAttribute: functions/Get-CmAttribute.md
      - Get-CmCertificate: functions/Get-CmCertificate.md
      - Get-CmClassAttribute: functions/Get-CmClassAttribute.md
      - Get-CmCredential: functions/Get-CmCredential.md
      - Get-CmCustomField: functions/Get-CmCustomField.md
      - Get-CmEngineFolder: functions/Get-CmEngineFolder.md
      - Get-CmIdentity: functions/Get-CmIdentity.md
      - Get-CmIdentityAttribute: functions/Get-CmIdentityAttribute.md
      - Get-CmObject: functions/Get-CmObject.md
      - Get-CmPermission: functions/Get-CmPermission.md
      - Get-CmTeam: functions/Get-CmTeam.md
      - Get-CmWorkflowTicket: functions/Get-CmWorkflowTicket.md
      - Import-CmCertificate: functions/Import-CmCertificate.md
      - Invoke-CmCertificateAction: functions/Invoke-CmCertificateAction.md
      - Move-CmObject: functions/Move-CmObject.md
      - New-CmCapiApplication: functions/New-CmCapiApplication.md
      - New-CmCertificate: functions/New-CmCertificate.md
      - New-CmCredential: functions/New-CmCredential.md
      - New-CmCustomField: functions/New-CmCustomField.md
      - New-CmDevice: functions/New-CmDevice.md
      - New-CmObject: functions/New-CmObject.md
      - New-CmPolicy: functions/New-CmPolicy.md
      - New-CmTeam: functions/New-CmTeam.md
      - Read-CmLog: functions/Read-CmLog.md
      - Remove-CmCertificate: functions/Remove-CmCertificate.md
      - Remove-CmCertificateAssociation: functions/Remove-CmCertificateAssociation.md
      - Remove-CmClient: functions/Remove-CmClient.md
      - Remove-CmEngineFolder: functions/Remove-CmEngineFolder.md
      - Remove-CmObject: functions/Remove-CmObject.md
      - Remove-CmPermission: functions/Remove-CmPermission.md
      - Remove-CmTeam: functions/Remove-CmTeam.md
      - Remove-CmTeamMember: functions/Remove-CmTeamMember.md
      - Remove-CmTeamOwner: functions/Remove-CmTeamOwner.md
      - Rename-CmObject: functions/Rename-CmObject.md
      - Revoke-CmGrant: functions/Revoke-CmGrant.md
      - Set-CmAttribute: functions/Set-CmAttribute.md
      - Set-CmCredential: functions/Set-CmCredential.md
      - Set-CmPermission: functions/Set-CmPermission.md
      - Set-CmWorkflowTicketStatus: functions/Set-CmWorkflowTicketStatus.md
      - Test-CmIdentity: functions/Test-CmIdentity.md
      - Test-CmObject: functions/Test-CmObject.md
      - Write-CmLog: functions/Write-CmLog.md
    - NGTS/Certificate Manager SaaS:
      - Export-TrustCertificate: functions/Export-TrustCertificate.md
      - Export-TrustReport: functions/Export-TrustReport.md
      - Find-TrustCertificate: functions/Find-TrustCertificate.md
      - Find-TrustCertificateInstance: functions/Find-TrustCertificateInstance.md
      - Find-TrustCertificateRequest: functions/Find-TrustCertificateRequest.md
      - Find-TrustLog: functions/Find-TrustLog.md
      - Find-TrustMachine: functions/Find-TrustMachine.md
      - Find-TrustMachineIdentity: functions/Find-TrustMachineIdentity.md
      - Get-TrustCertificate: functions/Get-TrustCertificate.md
      - Get-TrustCertificateAuthority: functions/Get-TrustCertificateAuthority.md
      - Get-TrustCertificateRequest: functions/Get-TrustCertificateRequest.md
      - Get-TrustCloudKeystore: functions/Get-TrustCloudKeystore.md
      - Get-TrustCloudProvider: functions/Get-TrustCloudProvider.md
      - Get-TrustConnector: functions/Get-TrustConnector.md
      - Get-TrustIssuingTemplate: functions/Get-TrustIssuingTemplate.md
      - Get-TrustMachine: functions/Get-TrustMachine.md
      - Get-TrustMachineIdentity: functions/Get-TrustMachineIdentity.md
      - Get-TrustSatellite: functions/Get-TrustSatellite.md
      - Get-TrustSatelliteWorker: functions/Get-TrustSatelliteWorker.md
      - Get-TrustTag: functions/Get-TrustTag.md
      - Get-TrustWebhook: functions/Get-TrustWebhook.md
      - Import-TrustCertificate: functions/Import-TrustCertificate.md
      - Invoke-TrustCertificateAction: functions/Invoke-TrustCertificateAction.md
      - Invoke-TrustWorkflow: functions/Invoke-TrustWorkflow.md
      - New-TrustCertificate: functions/New-TrustCertificate.md
      - New-TrustCloudKeystore: functions/New-TrustCloudKeystore.md
      - New-TrustCloudProvider: functions/New-TrustCloudProvider.md
      - New-TrustConnector: functions/New-TrustConnector.md
      - New-TrustMachine: functions/New-TrustMachine.md
      - New-TrustMachineCommonKeystore: functions/New-TrustMachineCommonKeystore.md
      - New-TrustMachineIis: functions/New-TrustMachineIis.md
      - New-TrustWebhook: functions/New-TrustWebhook.md
      - Remove-TrustCertificate: functions/Remove-TrustCertificate.md
      - Remove-TrustCloudKeystore: functions/Remove-TrustCloudKeystore.md
      - Remove-TrustCloudProvider: functions/Remove-TrustCloudProvider.md
      - Remove-TrustConnector: functions/Remove-TrustConnector.md
      - Remove-TrustIssuingTemplate: functions/Remove-TrustIssuingTemplate.md
      - Remove-TrustMachine: functions/Remove-TrustMachine.md
      - Remove-TrustMachineIdentity: functions/Remove-TrustMachineIdentity.md
      - Remove-TrustSatelliteWorker: functions/Remove-TrustSatelliteWorker.md
      - Remove-TrustTag: functions/Remove-TrustTag.md
      - Remove-TrustWebhook: functions/Remove-TrustWebhook.md
      - Set-TrustCertificate: functions/Set-TrustCertificate.md
      - Set-TrustCertificateRequest: functions/Set-TrustCertificateRequest.md
      - Set-TrustConnector: functions/Set-TrustConnector.md
      - Set-TrustIssuingTemplate: functions/Set-TrustIssuingTemplate.md
      - Set-TrustMachine: functions/Set-TrustMachine.md
      - Set-TrustMachineIdentity: functions/Set-TrustMachineIdentity.md
    - Certificate Manager SaaS only:
      - Add-CmsTeamMember: functions/Add-CmsTeamMember.md
      - Add-CmsTeamOwner: functions/Add-CmsTeamOwner.md
      - Get-CmsApplication: functions/Get-CmsApplication.md
      - Get-CmsTeam: functions/Get-CmsTeam.md
      - Get-CmsUser: functions/Get-CmsUser.md
      - Get-CmSystemStatus: functions/Get-CmSystemStatus.md
      - New-CmsApplication: functions/New-CmsApplication.md
      - New-CmsTeam: functions/New-CmsTeam.md
      - Remove-CmsApplication: functions/Remove-CmsApplication.md
      - Remove-CmsTeam: functions/Remove-CmsTeam.md
      - Remove-CmsTeamMember: functions/Remove-CmsTeamMember.md
      - Remove-CmsTeamOwner: functions/Remove-CmsTeamOwner.md
      - Set-CmsApplication: functions/Set-CmsApplication.md
      - Set-CmsTeam: functions/Set-CmsTeam.md
      - Set-CmsUser: functions/Set-CmsUser.md
