enum TppMetadataResult {
    Success = 0
    InvalidConfigObject = 1
    InvalidDN = 2
    InvalidName = 3
    InvalidItem = 4
    InvalidClass = 5
    InvalidMetadataObject = 6
    InvalidRights = 7
    ItemIsNull = 8
    ItemAlreadyExists = 9
    ItemTypeUnknown = 10
    ConfigCreateFailed = 11
    ConfigWriteFailed = 12
    ConfigDeleteFailed = 13
    MetadataInUse = 14
    NoAllowedValues = 15
    AllowedValueDoesNotExist = 16
    ValueNotInAllowedList = 17
    ItemNotValidForClass = 18
    NameTooLong = 19
    TooManyContainers = 20
    ConfigDnNotContainer = 21
    InvalidPolicyState = 22
    ConfigLockFailed = 23
    ConfigReadFailed = 24
    RemoteError = 25
}
