site_name: VenafiPS
site_url: https://github.com/venafi/venafips/
theme:
  name: mkdocs
include_sidebar: true
nav:
  - Home: '../README.md'
  - Changelog: '../CHANGELOG.md'
  - Functions: '/functions/'
