site_name: VenafiPS
site_url: https://venafi.github.io/venafips/
theme:
  name: material
  logo: images/v.svg
  features:
    - navigation.expand
  palette:
    primary: indigo
edit_uri: ""
nav:
  - Home: '../README.md'
  - Changelog: '../CHANGELOG.md'
  - Functions: '/functions/'
